### ISSUE TITLE
App carashes when pressing the stop button from the banner.

### ISSUE THREAD

**Issue by RAIERIN** [umbertoghio/react-native-screen-recorder#1]
![Screenshot_1663061193](https://user-images.githubusercontent.com/56987934/190977928-a9c165ef-e6b3-410d-a265-60dffe0cbdf7.png)
![Screen Shot 2022-09-13 at 3 12 07 PM](https://user-images.githubusercontent.com/56987934/190977931-24af127d-5075-4bff-8ca2-c7c3bc9629f7.png)

**Comment by umbertoghio** [comment]
Hi @RAIERIN , 
I managed to reproduce the problem, I'll investigate it today

**Comment by umbertoghio** [comment]
Hi, I've published version 0.1.2 and removed the stop recording from the notification.
Handling the stop from outside the app will require setting up listeners, for the moment I'll avoid that but feel free to send PRs
Have a nice day!

**Comment by RAIERIN** [comment]
Thanks!
