### ISSUE TITLE
TypeError: Cannot read property 'stopRecording' of null, js engine: hermes

### ISSUE THREAD

**Issue by alihaxan020** [umbertoghio/react-native-screen-recorder#10]
Hi @umbertoghio ,
I have installed the library. When I try to import then error occurred "TypeError: Cannot read property 'stopRecording' of null, js engine: hermes". Any Solution how to solve this error.
Screenshot:
![error](https://user-images.githubusercontent.com/68233556/235421186-e59fecb9-d19e-401d-93b4-aa912bac01f5.jpg)

Thanks,
Ali

**Comment by umbertoghio** [comment]
Hello Ali, 

please check the example in the main page, and also the example folder in this repo.

You need to import ScreenRecorder from 'react-native-screen-mic-recorder', not from NativeModules.
The object have attached the necessary methods, but needs to be used  from the class, i.e. ScreenRecorder.startRecording as it uses some stuff in the main class.

Hope it helps
