### ISSUE TITLE
Hi, stop recording from notification banner 

### ISSUE THREAD

**Issue by RAIERIN** [umbertoghio/react-native-screen-recorder#2]
Hi, can we add stop screen record from notification banner. And can we make the custom text of the permission dialog.

**Comment by umbertoghio** [comment]
Hi @RAIERIN 

that will require a bit of config when setting up recording, particularly a listener / function to be called when the banner is pressed.

I'll look into it this weekend

**Comment by RAIERIN** [comment]
Thanks @umbertoghio.

**Comment by umbertoghio** [comment]
Hi @RAIERIN , I've made a new release, now if you add a androidBannerStopRecordingHandler callback function it will show and handle the future properly.

The permission dialog 
![image](https://user-images.githubusercontent.com/25666241/194713052-8d229a73-833f-4127-955d-7cf20e668ed9.png)
is handled by Android, I haven't found a way to customize it

Feel free to send PRs in case you figure it out!

**Comment by RAIERIN** [comment]
Thanks @umbertoghio
