### ISSUE TITLE
App stops screen recording while in app in minimized in ios.

### ISSUE THREAD

**Issue by RAIERIN** [umbertoghio/react-native-screen-recorder#5]
Why does screen recording stops when app is closed but resumes when app opens. But the recorded video is blank.

**Comment by umbertoghio** [comment]
It seems to be dependent on the underlying library and permissions, the scope of the app is to record the screen from within the app, recording the screen also in other app might be a security concern

**Comment by RAIERIN** [comment]
@umbertoghio is there any way we can record screen while in background too. Any idea about that.

**Comment by umbertoghio** [comment]
Check this out, I don't think it is possible on Android for all applications https://developer.android.com/guide/topics/media/av-capture

**Comment by RAIERIN** [comment]
@umbertoghio any idea or resources you have on ios.

**Comment by umbertoghio** [comment]
The only way I know is https://developer.apple.com/documentation/replaykit , but is used only within the app. 
You can ask the user to record the screen from the control center and then select the video, otherwise due to security reason I don't think there's a feasible way

**Comment by RAIERIN** [comment]
@umbertoghio Thanks!
