### ISSUE TITLE
System audio.

### ISSUE THREAD

**Issue by RAIERIN** [umbertoghio/react-native-screen-recorder#6]
Is there any way we can allow only system audio while recording.

**Comment by umbertoghio** [comment]
Sure, just set mic:false in the options you pass to to the startRecording

**Comment by RAIERIN** [comment]
@umbertoghio but it doesn't record internal audio. Is there any way we can do that.

**Comment by umbertoghio** [comment]
Well...it should, in the app I uses this library I get the mic mixed with the app audio.
Maybe you are trying to record audio from other apps? Not sure if this hits against some privacy / security restrictions.

**Comment by fizawisedv** [comment]
Hi @umbertoghio, I guess the app audio is not recording for me either. I have checked with playing video in [react-native-video](https://www.npmjs.com/package/react-native-video) where the video's audio is not getting recorded. In my app, I majorly have WebRTC audio ([react-native-webrtc](https://www.npmjs.com/package/react-native-webrtc)) which is also not getting recorded.
I have tested in android 12 and 11. And on ios 16.

Also, I have noticed that the recorded video does not have an audio track.

@RAIERIN did you manage to get it working somehow?

**Comment by umbertoghio** [comment]
Hi @fizawisedv , 

have you tried enabling the mic? does it record from it?
@RAIERIN  was trying to record audio outside the application or while in background, while recording in-app audio with microphone should be fine (I have it on a couple of app both iOS and Android).

You may also want to give a try to https://github.com/yutasuzuki/react-native-record-screen , the original project I forked from

**Comment by RAIERIN** [comment]
@fizawisedv for the system audio we have to use different method. It is quite complicated. I couldn't find any packages. We have to record the screen, and there is api can record the internal audio in android, and we have to merge it once the screen recording finishes.
