### ISSUE TITLE
Stop is throwing an error on IOS

### ISSUE THREAD

**Issue by Milkhan** [umbertoghio/react-native-screen-recorder#8]
When I stop the recording, I get this error on IOS:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriterInput markAsFinished] Cannot call method when status is 0'
Any idea what causes this?

Thank you

**Comment by umbertoghio** [comment]
Hello Milkhan, 
sorry for the late reply, I was in holiday.
Do you have any update on the issue?
If you could give me more information I can try to investigate further, for example:
Version of react native, version of iOS, simulator or device, permissions configuration, etc.

**Comment by cheeka13** [comment]
I still got this issue when stopping.
react native 0.69.5
simulator ios 16.4

**Comment by umbertoghio** [comment]
Hi @cheeka13 , 
I had a look at the IOS code and searched for the specific error message without luck...

since the last time I've released a new version of the library, have you tried to update?
I suggest also to try it on a real device and one last attempt on a blank project, in case some other library maybe interfere with it (it would be odd).
Sorry but I could not figure out why is doing it (I'm successfully running this library on several complex apps without errors).

**Comment by cheeka13** [comment]
> I had a look at the IOS code and searched for the specific error message without luck...

Hi,
I got the same issue with the original lib react-native-record-screen and still didn't figure it out. Thank you.

**Comment by cheeka13** [comment]
> Hi @cheeka13 , I had a look at the IOS code and searched for the specific error message without luck...
> 
> since the last time I've released a new version of the library, have you tried to update? I suggest also to try it on a real device and one last attempt on a blank project, in case some other library maybe interfere with it (it would be odd). Sorry but I could not figure out why is doing it (I'm successfully running this library on several complex apps without errors).

Btw, am I able to change the size of recording dimension on android?

**Comment by umbertoghio** [comment]
Hi, 
no, you can't set the recording dimensions on Android, but if you fork the project you may be able to pass more config to hbrecorder.

About the issue one time I figured out an issue by starting from scratch on a blank project, adding the problematic library that worked correctly and then added back the rest of the code / dependencies in chunks until I found the conflict...a bit time consuming but it helped. 

Hope you resolve your issue soon!

**Comment by cheeka13** [comment]
Thank you. Have a nice day!
