### ISSUE TITLE
Change/overwrite description for screen capture permission dialog box

### ISSUE THREAD

**Issue by fizawisedv** [umbertoghio/react-native-screen-recorder#9]
Hello,

I am not sure how I can change the permission description. The below-attached screenshot shows what is currently displayed. Can you please guide how or from where I can change/overwrite the description stating 'This application will capture your screen and you will not have a chance to review it'?

![1FF26C4F-56C5-4B55-9611-B2624167B0EE-small](https://user-images.githubusercontent.com/87169945/221914318-9e6b2eb9-a400-494c-8463-a734a03cbd70.png)

Thanks.

**Comment by umbertoghio** [comment]
Hi, 
I believe this message comes from Apple's RPScreenRecorder from ReplayKit library, I haven't found a way to customize this message so far...
